/*
 * This Java source file was generated by the Gradle 'init' task.
 */


public interface PDFSeparator {

    List<PDDocument> splitPDF(File pdf);

    static PDFSeparator create() {
        return new SeparatorHelper();
    }
}
